// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAefimDMd9sMbWwHMMbdMUtQxFcoSbPz2A',
    appId: '1:36587859772:web:31f149c03e8d8897093839',
    messagingSenderId: '36587859772',
    projectId: 'aharexpress-master',
    authDomain: 'aharexpress-master.firebaseapp.com',
    storageBucket: 'aharexpress-master.firebasestorage.app',
    measurementId: 'G-BLJ44NG0F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfaTtG-VQvnU2W3rrMw-PTEQ4NAoxIdOQ',
    appId: '1:36587859772:android:652b288d7709a2c3093839',
    messagingSenderId: '36587859772',
    projectId: 'aharexpress-master',
    storageBucket: 'aharexpress-master.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTauh9WhDGYdz-Rt4tiEGwgUCs6F8qO5I',
    appId: '1:36587859772:ios:0cb4bd564248d0fc093839',
    messagingSenderId: '36587859772',
    projectId: 'aharexpress-master',
    storageBucket: 'aharexpress-master.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTauh9WhDGYdz-Rt4tiEGwgUCs6F8qO5I',
    appId: '1:36587859772:ios:0cb4bd564248d0fc093839',
    messagingSenderId: '36587859772',
    projectId: 'aharexpress-master',
    storageBucket: 'aharexpress-master.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAefimDMd9sMbWwHMMbdMUtQxFcoSbPz2A',
    appId: '1:36587859772:web:f28c81f677aa3fd0093839',
    messagingSenderId: '36587859772',
    projectId: 'aharexpress-master',
    authDomain: 'aharexpress-master.firebaseapp.com',
    storageBucket: 'aharexpress-master.firebasestorage.app',
    measurementId: 'G-1WTF6BQKMT',
  );

}